// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { SessionProvider } from "next-auth/react";
// import NavigationBar from "@/components/NavigationBar";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//           <SessionProvider>
//             <NavigationBar />
//             {children}
//           </SessionProvider>
//       </body>
//     </html>
//   );
// }
import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { SessionProvider } from "next-auth/react";
import NavigationBar from "@/components/NavigationBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "電子パンフレットアプリ",
  description:
    "既存の地図やフロアプランを活かしながら、インタラクティブな電子パンフレットに変換。訪問者に最高の体験を提供します。",
  openGraph: {
    type: "website",
    locale: "ja_JP",
    url: "https://timer-4l94k5tg0-yudaishimamuras-projects.vercel.app/",
    siteName: "電子パンフレットアプリ",
    title: "電子パンフレットアプリ",
    description: "地図をインタラクティブに変える電子パンフレットアプリ",
    images: [
      {
        url: "/ffff.jpeg",
        width: 1200,
        height: 630,
        alt: "電子パンフレットアプリ",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "電子パンフレットアプリ",
    description: "地図をインタラクティブに変える電子パンフレットアプリ",
    images: ["/api/og"],
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <SessionProvider>
              <NavigationBar /> 
            {children}
          </SessionProvider>
      </body>
    </html>
  )
}

